[[mgr.prepend_keymap]]
on = [ "!" ]
run = 'shell "$SHELL" --block --confirm'
desc = "Open shell here"

[[mgr.prepend_keymap]]
on  = "M"
run = "plugin mount"

[[mgr.prepend_keymap]]
on   = "T"
run  = "plugin toggle-pane max-preview"
desc = "Maximize or restore the preview pane"

[[mgr.prepend_keymap]]
on  = [ "g", "m"]
run = 'cd "/run/media/$USER"'
desc = "Go to mount folder"

[[mgr.prepend_keymap]]
on  = [ "g", "s"]
run = 'cd "$HOME/share"'
desc = "Go to share folder"

[[mgr.prepend_keymap]]
on  = [ "g", "w"]
run = 'cd "$HOME/work/2026/"'
desc = "Go to work folder"

[[mgr.prepend_keymap]]
on  = [ "g", "p"]
run = 'cd "$HOME/work/publications/"'
desc = "Go to publications folder"

[[mgr.prepend_keymap]]
on  = [ "g", "W"]
run = 'cd "$HOME/wiki"'
desc = "Go to WIKI folder"

[[mgr.prepend_keymap]]
on  = [ "g", "y"]
run = 'cd "$HOME/work/yara"'
desc = "Go to YARA folder"
