# yazi.toml

[mgr]
sort_by = "natural"
sort_dir_first = true
linemode = "size"
show_hidden = true
# sort_by = "modified"

[preview]
wrap = "yes"
tab_size = 2

[opener]
vim = [
    { run = 'vim "$@"', desc = "Vim edit", block = true, for = "unix"},
    { run = 'vim -R "$@"', desc = "Vim readonly", block = true, for = "unix"}

    ]
hexyl = [
    { run = 'hexyl "$@" | $PAGER -r', desc = "Hexyl", block = true, for = "unix"},
    ]


diec = [
    { run = 'die "$@"', desc="DIE gui", orphan = true},
    { run = 'diec --heuristicscan --verbose "$@" | $PAGER -r', desc="DIE console", block = true, for = "unix"},
    ]

floss = [
    { run = 'floss --only static -- "$@" | $PAGER -r', desc = "Floss", block = true, for = "unix"},
    ]


[open]
prepend_rules = [
    { mime = "application/hta", use = [ "edit" , "reveal" ] },
]
append_rules = [
    { url = "*", use = [ "open", "reveal", "hexyl", "diec", "vim", "floss" ] }
]
[plugin]
prepend_previewers = [
    { url = "*.md", run = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"' },
    { url = "*.idb", run = "noop" },
    { url = "*.i64", run = "noop" },
    { url = "*.yar", run = "code" },
    { url = "*.yara", run = "code" },
    { url = "*.eml", run = "code" },
    { url = "*.bin", run = 'piper -- hexyl --border=none --terminal-width=$w "$1"' },
    { url = "*.ps1", run = "code" },
    { mime = "message/rfc822", run = "code" },
    { mime = "application/hta", run = "code" },
    { mime = "application/octet-stream", run = 'piper -- hexyl --border=none --terminal-width=$w "$1"' },
    ]

append_previewers = [
]

[[plugin.prepend_fetchers]]
group = "git"
url = "*"
run  = "git"

[[plugin.prepend_fetchers]]
group = "git"
url = "*/"
run  = "git"
